framework:
    notifier:
        channel_policy:
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: sarra.benhamida@esprit.tn }
