when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
<<<<<<< HEAD
        profiler:
            only_exceptions: false
            collect_serializer_data: true
=======
        profiler: { only_exceptions: false }
>>>>>>> New/integ

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
